// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD83SWA155J8Q2fzkl-mr4doP6-uZWUi90',
    appId: '1:881451589364:web:9c98d890563f7041b508a1',
    messagingSenderId: '881451589364',
    projectId: 'yoga-app-b38da',
    authDomain: 'yoga-app-b38da.firebaseapp.com',
    storageBucket: 'yoga-app-b38da.appspot.com',
    measurementId: 'G-N6DV6T8RQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdq6TQHj1z7WHDoWD_NdR31OOs3wrtmIo',
    appId: '1:881451589364:android:885f29ea15cfbb22b508a1',
    messagingSenderId: '881451589364',
    projectId: 'yoga-app-b38da',
    storageBucket: 'yoga-app-b38da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_dmYbgGzsVwUCXTXSabdDFlwB5BLUrxE',
    appId: '1:881451589364:ios:8e725b1fdbca9f3cb508a1',
    messagingSenderId: '881451589364',
    projectId: 'yoga-app-b38da',
    storageBucket: 'yoga-app-b38da.appspot.com',
    iosBundleId: 'com.example.blocCheckbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_dmYbgGzsVwUCXTXSabdDFlwB5BLUrxE',
    appId: '1:881451589364:ios:8e725b1fdbca9f3cb508a1',
    messagingSenderId: '881451589364',
    projectId: 'yoga-app-b38da',
    storageBucket: 'yoga-app-b38da.appspot.com',
    iosBundleId: 'com.example.blocCheckbox',
  );
}
